// TOEIC 필수 단어 데이터
// id: 고유번호, word: 영단어, pos: 품사, meaning: 뜻, example: 예문, exampleKo: 예문 해석
const VOCAB_DATA = [
  { id: 1, word: "accommodate", pos: "v.", meaning: "수용하다, 편의를 도모하다", example: "The hotel can accommodate up to 300 guests.", exampleKo: "그 호텔은 최대 300명의 손님을 수용할 수 있다." },
  { id: 2, word: "acquire", pos: "v.", meaning: "취득하다, 획득하다", example: "The company plans to acquire a smaller competitor.", exampleKo: "그 회사는 더 작은 경쟁사를 인수할 계획이다." },
  { id: 3, word: "allocate", pos: "v.", meaning: "할당하다, 배분하다", example: "The manager decided to allocate the budget to three departments.", exampleKo: "매니저는 예산을 세 개 부서에 배분하기로 결정했다." },
  { id: 4, word: "applicant", pos: "n.", meaning: "지원자, 신청자", example: "Each applicant must submit a resume by Friday.", exampleKo: "각 지원자는 금요일까지 이력서를 제출해야 한다." },
  { id: 5, word: "appraisal", pos: "n.", meaning: "평가, 감정", example: "The company conducts a performance appraisal every year.", exampleKo: "그 회사는 매년 성과 평가를 실시한다." },
  { id: 6, word: "approve", pos: "v.", meaning: "승인하다", example: "The manager will approve the new marketing plan tomorrow.", exampleKo: "매니저는 내일 새로운 마케팅 계획을 승인할 것이다." },
  { id: 7, word: "authorize", pos: "v.", meaning: "권한을 부여하다, 승인하다", example: "Only the director can authorize contract signings.", exampleKo: "오직 이사만이 계약 서명을 승인할 수 있다." },
  { id: 8, word: "beneficial", pos: "adj.", meaning: "유익한, 이로운", example: "Regular exercise is beneficial to your health.", exampleKo: "규칙적인 운동은 건강에 유익하다." },
  { id: 9, word: "candidate", pos: "n.", meaning: "후보자", example: "She is the strongest candidate for the position.", exampleKo: "그녀는 그 직위에 가장 유력한 후보자이다." },
  { id: 10, word: "colleague", pos: "n.", meaning: "동료", example: "I discussed the project with a colleague.", exampleKo: "나는 한 동료와 그 프로젝트에 대해 논의했다." },
  { id: 11, word: "compensation", pos: "n.", meaning: "보상, 보수", example: "The compensation package includes health insurance.", exampleKo: "보상 패키지에는 건강 보험이 포함된다." },
  { id: 12, word: "comply", pos: "v.", meaning: "준수하다, 따르다", example: "All employees must comply with the safety regulations.", exampleKo: "모든 직원은 안전 규정을 준수해야 한다." },
  { id: 13, word: "confidential", pos: "adj.", meaning: "기밀의", example: "The documents contain confidential information.", exampleKo: "그 서류에는 기밀 정보가 포함되어 있다." },
  { id: 14, word: "consecutive", pos: "adj.", meaning: "연속적인", example: "Sales have increased for five consecutive months.", exampleKo: "매출이 다섯 달 연속으로 증가했다." },
  { id: 15, word: "consolidate", pos: "v.", meaning: "통합하다", example: "The two firms decided to consolidate their operations.", exampleKo: "두 회사는 사업을 통합하기로 결정했다." },
  { id: 16, word: "constitute", pos: "v.", meaning: "구성하다", example: "Small businesses constitute a large part of the economy.", exampleKo: "소기업들은 경제의 큰 부분을 구성한다." },
  { id: 17, word: "consult", pos: "v.", meaning: "상담하다, 참고하다", example: "Please consult the manual before installation.", exampleKo: "설치 전에 설명서를 참고하세요." },
  { id: 18, word: "contribute", pos: "v.", meaning: "기여하다", example: "Every team member is expected to contribute to the project's success.", exampleKo: "모든 팀원은 프로젝트의 성공에 기여할 것으로 기대된다." },
  { id: 19, word: "convenient", pos: "adj.", meaning: "편리한", example: "The new office location is more convenient for clients.", exampleKo: "새 사무실 위치는 고객들에게 더 편리하다." },
  { id: 20, word: "corporate", pos: "adj.", meaning: "기업의, 회사의", example: "The corporate headquarters is located downtown.", exampleKo: "본사는 시내 중심가에 위치해 있다." },
  { id: 21, word: "deduct", pos: "v.", meaning: "공제하다", example: "The company will deduct taxes from your monthly salary.", exampleKo: "회사는 월급에서 세금을 공제할 것이다." },
  { id: 22, word: "delegate", pos: "v.", meaning: "위임하다", example: "The manager decided to delegate the task to his assistant.", exampleKo: "매니저는 그 업무를 조수에게 위임하기로 결정했다." },
  { id: 23, word: "demonstrate", pos: "v.", meaning: "입증하다, 시연하다", example: "The sales rep will demonstrate how the machine works.", exampleKo: "영업 담당자가 기계 작동법을 시연할 것이다." },
  { id: 24, word: "depict", pos: "v.", meaning: "묘사하다", example: "The graph will depict the company's growth over five years.", exampleKo: "그 그래프는 회사의 5년간 성장을 보여줄 것이다." },
  { id: 25, word: "designate", pos: "v.", meaning: "지정하다", example: "The board decided to designate a conference room for the meeting.", exampleKo: "이사회는 그 회의를 위해 회의실을 지정하기로 결정했다." },
  { id: 26, word: "discrepancy", pos: "n.", meaning: "불일치, 차이", example: "There is a discrepancy between the two reports.", exampleKo: "두 보고서 사이에 불일치가 있다." },
  { id: 27, word: "dispatch", pos: "v.", meaning: "발송하다, 파견하다", example: "The warehouse will dispatch the order within two days.", exampleKo: "창고는 이틀 이내에 주문품을 발송할 것이다." },
  { id: 28, word: "distribute", pos: "v.", meaning: "분배하다, 배포하다", example: "The staff will distribute the handouts before the seminar begins.", exampleKo: "직원들은 세미나가 시작되기 전에 유인물을 배포할 것이다." },
  { id: 29, word: "durable", pos: "adj.", meaning: "내구성이 있는", example: "This material is more durable than plastic.", exampleKo: "이 재료는 플라스틱보다 내구성이 좋다." },
  { id: 30, word: "eligible", pos: "adj.", meaning: "자격이 있는", example: "Only full-time employees are eligible for the bonus.", exampleKo: "정규직 직원만 보너스를 받을 자격이 있다." },
  { id: 31, word: "endorse", pos: "v.", meaning: "지지하다, 보증하다", example: "The famous athlete agreed to endorse the sports brand.", exampleKo: "그 유명 운동선수는 그 스포츠 브랜드를 보증하기로 동의했다." },
  { id: 32, word: "enhance", pos: "v.", meaning: "향상시키다", example: "The new software will enhance productivity.", exampleKo: "새 소프트웨어는 생산성을 향상시킬 것이다." },
  { id: 33, word: "enroll", pos: "v.", meaning: "등록하다", example: "Employees can enroll in the training program online.", exampleKo: "직원들은 온라인으로 교육 프로그램에 등록할 수 있다." },
  { id: 34, word: "estimate", pos: "v./n.", meaning: "추정하다, 견적", example: "The contractor gave us an estimate for the repairs.", exampleKo: "그 도급업자는 우리에게 수리 견적을 주었다." },
  { id: 35, word: "evaluate", pos: "v.", meaning: "평가하다", example: "Managers evaluate employee performance every quarter.", exampleKo: "관리자들은 분기마다 직원 성과를 평가한다." },
  { id: 36, word: "exceed", pos: "v.", meaning: "초과하다", example: "Sales this quarter are likely to exceed our expectations.", exampleKo: "이번 분기 매출은 우리의 기대치를 초과할 것 같다." },
  { id: 37, word: "expertise", pos: "n.", meaning: "전문 지식", example: "She has expertise in financial planning.", exampleKo: "그녀는 재무 계획에 전문 지식을 가지고 있다." },
  { id: 38, word: "facilitate", pos: "v.", meaning: "촉진하다, 용이하게 하다", example: "The new system will facilitate faster communication.", exampleKo: "새 시스템은 더 빠른 의사소통을 촉진할 것이다." },
  { id: 39, word: "feasible", pos: "adj.", meaning: "실현 가능한", example: "It is not feasible to finish the project by tomorrow.", exampleKo: "내일까지 프로젝트를 끝내는 것은 실현 가능하지 않다." },
  { id: 40, word: "fluctuate", pos: "v.", meaning: "변동하다", example: "Stock prices fluctuate throughout the day.", exampleKo: "주가는 하루 종일 변동한다." },
  { id: 41, word: "forecast", pos: "v./n.", meaning: "예측하다, 예보", example: "Analysts forecast steady growth next year.", exampleKo: "분석가들은 내년에 꾸준한 성장을 예측한다." },
  { id: 42, word: "fundamental", pos: "adj.", meaning: "근본적인", example: "Trust is fundamental to any business relationship.", exampleKo: "신뢰는 모든 사업 관계에 근본적이다." },
  { id: 43, word: "generate", pos: "v.", meaning: "발생시키다, 창출하다", example: "The new product is expected to generate a lot of revenue.", exampleKo: "그 신제품은 많은 수익을 창출할 것으로 기대된다." },
  { id: 44, word: "implement", pos: "v.", meaning: "시행하다", example: "The company will implement a new policy next month.", exampleKo: "회사는 다음 달에 새로운 정책을 시행할 것이다." },
  { id: 45, word: "incentive", pos: "n.", meaning: "장려책, 유인책", example: "Employees receive an incentive for meeting their targets.", exampleKo: "직원들은 목표 달성 시 장려책을 받는다." },
  { id: 46, word: "inevitable", pos: "adj.", meaning: "불가피한", example: "Delays are inevitable during the rainy season.", exampleKo: "우기 동안에는 지연이 불가피하다." },
  { id: 47, word: "initiative", pos: "n.", meaning: "계획, 주도권", example: "The company launched a new environmental initiative.", exampleKo: "그 회사는 새로운 환경 계획을 시작했다." },
  { id: 48, word: "inquiry", pos: "n.", meaning: "문의", example: "Please direct any inquiry to the customer service desk.", exampleKo: "문의 사항은 고객 서비스 데스크로 보내주세요." },
  { id: 49, word: "instrumental", pos: "adj.", meaning: "중요한 역할을 하는", example: "She was instrumental in securing the new contract.", exampleKo: "그녀는 새 계약을 따내는 데 중요한 역할을 했다." },
  { id: 50, word: "inventory", pos: "n.", meaning: "재고", example: "We need to check the inventory before ordering more supplies.", exampleKo: "더 많은 물품을 주문하기 전에 재고를 확인해야 한다." },
  { id: 51, word: "invoice", pos: "n.", meaning: "송장, 청구서", example: "Please pay the invoice within 30 days.", exampleKo: "청구서는 30일 이내에 지불해 주세요." },
  { id: 52, word: "legitimate", pos: "adj.", meaning: "합법적인, 정당한", example: "The company has a legitimate reason for the delay.", exampleKo: "그 회사는 지연에 대한 정당한 이유가 있다." },
  { id: 53, word: "logistics", pos: "n.", meaning: "물류", example: "The logistics team handles all shipping arrangements.", exampleKo: "물류팀이 모든 배송 준비를 담당한다." },
  { id: 54, word: "maintenance", pos: "n.", meaning: "유지보수", example: "The building requires regular maintenance.", exampleKo: "그 건물은 정기적인 유지보수가 필요하다." },
  { id: 55, word: "mandatory", pos: "adj.", meaning: "의무적인, 필수의", example: "Attendance at the safety training is mandatory.", exampleKo: "안전 교육 참석은 필수이다." },
  { id: 56, word: "merger", pos: "n.", meaning: "합병", example: "The merger between the two banks was finalized last week.", exampleKo: "두 은행 간의 합병이 지난주에 마무리되었다." },
  { id: 57, word: "negotiate", pos: "v.", meaning: "협상하다", example: "The union tried to negotiate better working conditions.", exampleKo: "노조는 더 나은 근무 조건을 협상하려 했다." },
  { id: 58, word: "notify", pos: "v.", meaning: "통지하다", example: "Please notify us of any changes in advance.", exampleKo: "변경 사항이 있으면 미리 저희에게 통지해 주세요." },
  { id: 59, word: "obligation", pos: "n.", meaning: "의무", example: "The company has an obligation to pay its employees on time.", exampleKo: "회사는 직원들에게 제때 급여를 지급할 의무가 있다." },
  { id: 60, word: "outstanding", pos: "adj.", meaning: "뛰어난, 미지불된", example: "There is still an outstanding balance on the account.", exampleKo: "계좌에 아직 미지불 잔액이 있다." },
  { id: 61, word: "overhead", pos: "n.", meaning: "간접비, 운영비", example: "The company reduced overhead by moving to a smaller office.", exampleKo: "회사는 더 작은 사무실로 이전하여 간접비를 줄였다." },
  { id: 62, word: "postpone", pos: "v.", meaning: "연기하다", example: "The manager decided to postpone the meeting until next week.", exampleKo: "매니저는 회의를 다음 주로 연기하기로 결정했다." },
  { id: 63, word: "prerequisite", pos: "n.", meaning: "전제 조건", example: "Basic computer skills are a prerequisite for this job.", exampleKo: "기본적인 컴퓨터 기술은 이 직무의 전제 조건이다." },
  { id: 64, word: "proficient", pos: "adj.", meaning: "능숙한", example: "Applicants should be proficient in English and Spanish.", exampleKo: "지원자는 영어와 스페인어에 능숙해야 한다." },
  { id: 65, word: "prominent", pos: "adj.", meaning: "저명한, 두드러진", example: "The prominent scientist gave a lecture at the university.", exampleKo: "그 저명한 과학자는 대학에서 강의를 했다." },
  { id: 66, word: "prospective", pos: "adj.", meaning: "장래의, 잠재적인", example: "Prospective buyers can schedule a tour of the property.", exampleKo: "잠재 구매자들은 부동산 견학을 예약할 수 있다." },
  { id: 67, word: "provision", pos: "n.", meaning: "조항, 공급", example: "The contract includes a provision for early termination.", exampleKo: "그 계약에는 조기 해지에 대한 조항이 포함되어 있다." },
  { id: 68, word: "reimburse", pos: "v.", meaning: "환급하다, 상환하다", example: "The company will reimburse you for travel expenses.", exampleKo: "회사는 출장 경비를 환급해 줄 것이다." },
  { id: 69, word: "renowned", pos: "adj.", meaning: "유명한", example: "The renowned chef opened a new restaurant downtown.", exampleKo: "그 유명한 요리사는 시내에 새 식당을 열었다." },
  { id: 70, word: "resolve", pos: "v.", meaning: "해결하다", example: "The two parties agreed to resolve the dispute through mediation.", exampleKo: "양측은 중재를 통해 분쟁을 해결하기로 합의했다." },
  { id: 71, word: "revenue", pos: "n.", meaning: "수익, 세입", example: "The company's revenue increased by 20 percent this year.", exampleKo: "회사의 수익이 올해 20퍼센트 증가했다." },
  { id: 72, word: "subsidiary", pos: "n.", meaning: "자회사", example: "The corporation has a subsidiary in Germany.", exampleKo: "그 기업은 독일에 자회사를 두고 있다." },
  { id: 73, word: "substantial", pos: "adj.", meaning: "상당한", example: "The company made a substantial investment in research.", exampleKo: "그 회사는 연구에 상당한 투자를 했다." },
  { id: 74, word: "supervise", pos: "v.", meaning: "감독하다", example: "She will supervise a team of ten employees.", exampleKo: "그녀는 열 명의 직원으로 구성된 팀을 감독할 것이다." },
  { id: 75, word: "sustain", pos: "v.", meaning: "지속하다, 유지하다", example: "The company managed to sustain growth despite the recession.", exampleKo: "그 회사는 불황에도 불구하고 성장을 지속할 수 있었다." },
  { id: 76, word: "tentative", pos: "adj.", meaning: "잠정적인", example: "We have a tentative schedule for the conference.", exampleKo: "우리는 학회를 위한 잠정적인 일정을 가지고 있다." },
  { id: 77, word: "terminate", pos: "v.", meaning: "종료하다, 해지하다", example: "The company can terminate the contract with 30 days' notice.", exampleKo: "회사는 30일 전 통지로 계약을 해지할 수 있다." },
  { id: 78, word: "transaction", pos: "n.", meaning: "거래", example: "Every transaction is recorded in the database.", exampleKo: "모든 거래는 데이터베이스에 기록된다." },
  { id: 79, word: "unanimous", pos: "adj.", meaning: "만장일치의", example: "The board reached a unanimous decision.", exampleKo: "이사회는 만장일치로 결정을 내렸다." },
  { id: 80, word: "versatile", pos: "adj.", meaning: "다재다능한, 다용도의", example: "This tool is versatile and can be used for many tasks.", exampleKo: "이 도구는 다용도로 여러 작업에 사용될 수 있다." },
];
